const hotelsTownLists = [
    {
        title:"Dubai",
        data :[
            {id:"39", label:"Abu Dhabi (Абу Даби)"},
            {id:"43", label:"Dubai (Дубай)"},
            {id:"28", label:"Dubai (Deira)"},
            {id:"139", label:"NO USE"},
            {id:"37", label:"Abu Dhabi"},
            {id:"32", label:"Ajman"},
            {id:"104", label:"Al Ain"},
            {id:"102", label:"Dubai (DownTown)"},
            {id:"31", label:"Dubai (Al Barsha)"},
            {id:"49", label:"Dubai (Bur Dubai)"},
            {id:"107", label:"Dubai (Business Bay)"},
            {id:"52", label:"Dubai (Desert)"},
            {id:"51", label:"Dubai (Dubai Marina)"},
            {id:"134", label:"Dubai (Dubailand)"},
            {id:"108", label:"Dubai (Emirates Hills)"},
            {id:"132", label:"Dubai (Festival City)"},
            {id:"136", label:"Dubai (Financial Centre)"},
            {id:"34", label:"Dubai (Jebel Ali)"},
            {id:"29", label:"Dubai (Jumeirah)"},
            {id:"103", label:"Dubai (Media City)"},
            {id:"142", label:"Dubai (Naser Square)"},
            {id:"30", label:"Dubai (Palm Jumeirah)"},
            {id:"53", label:"Dubai (Tecom)"},
            {id:"140", label:"International City"},
            {id:"33", label:"Fujairah"},
            {id:"35", label:"Ras Al Khaimah"},
            {id:"36", label:"Sharjah"},
            {id:"70", label:"Umm Al Quwain"},
            {id:"147", label:"ALL UAE HOTELS"},
            {id:"50", label:"Dubai (Sheikh Zaed Road)"},
            {id:"148", label:"Khalifa Bin Zayed Road"},
            {id:"105", label:"Dubai (JBR)"},
            {id:"169", label:"Dubai (Al Qusais)"},
            {id:"174", label:"Dubai (Hatta)"},
            {id:"186", label:"Dubai (BluewatersIsland)"},
            {id:"205", label:"Dubai (Nad Al Sheba)"},
            {id:"124", label:"Al Maktoum"},
            {id:"211", label:"Dubai (Ras Al Khor)"},
            {id:"212", label:"Dubai (Jumeirah Village)"},
            {id:"214", label:"Dubai (JLT)"},
            {id:"215", label:"Dubai (Silicon Oasis)"},
            {id:"216", label:"Dubai (Production City)"},
            {id:"217", label:"Dubai (Motor City)"},
            {id:"218", label:"Dubai (World Central)" },
        ]
    }
]