-- AlterTable
ALTER TABLE "Flight" ADD COLUMN     "isWithReturn" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "returnEndTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "returnStartTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
